### ISSUE TITLE
Morse alfabet not valid by stardard

### ISSUE THREAD

**Issue by Konstantin8105** [alwindoss/morse#10]
**Describe the bug**
Morse alfabet not valid by stardard

**To Reproduce**
see Go tests:
```go
expected := "-- -.-- / -. .- -- . / .. ... / .- .-.. .-- .. -. / -.. --- ... ..."
```

**Expected behavior**
```go
expected := "-- -.--  -. .- -- . .. ... .- .-.. .-- .. -. -.. --- ... ..."
```

**Screenshots**
No.

**Environment (please complete the following information with `go env` output):**
No need
 
**Additional context**
for more information see `Recommendation ITU-R M.1677-1`
http://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1677-1-200910-I!!PDF-E.pdf

**Comment by alwindoss** [comment]
I wasn't able to access the link to the PDF. However, if I use the online Morse Code Translator it replaces space with `/`
[Online Translator](https://morsecode.scphillips.com/translator.html)

**Comment by alwindoss** [comment]
Closing this issue seeing there is no response from the creator of the issue.
