### ISSUE TITLE
Change github statistic

### ISSUE THREAD

**Issue by Konstantin8105** [alwindoss/morse#13]
**Is your feature request related to a problem? Please describe.**
Github statistic use all files(sources, scripts,...) for show statistic.
But some projects avoid files of scripts, testdata, CI files in Github statistic.

**Describe the solution you'd like**
Add file : `.gitattributes`
Example of use: https://github.com/Konstantin8105/c4go/blob/master/.gitattributes

**Describe alternatives you've considered**
Ignored

**Additional context**
See Article https://hackernoon.com/how-to-change-repo-language-in-github-c3e07819c5bb

**Comment by alwindoss** [comment]
Raised a PR for this issue [PR](https://github.com/alwindoss/morse/pull/14)

**Comment by alwindoss** [comment]
Closed as part of the PR https://github.com/alwindoss/morse/pull/14
