### ISSUE TITLE
special characters is supported?

### ISSUE THREAD

**Issue by Declarcall** [alwindoss/morse#17]
**Is your feature request related to a problem? Please describe.**
Excuse me, special characters, such as: ":", "=", "&", is not supported yet?
Example:
```go
package main

import (
	"strings"
	"fmt"
	"github.com/alwindoss/morse"
)


func main()  {
	h:=morse.NewHacker()
	encode,_:=h.Encode(strings.NewReader(":=:&=:"))
	decode,_:=h.Decode(strings.NewReader(string(encode)))
	fmt.Println(string(decode))
}
```
Output empty string.

**Comment by alwindoss** [comment]
@Declarcall you are right these characters are not supported yet, you can raise a PR for this, add the mappings to the `constants.go` I can accept the PR

**Comment by alwindoss** [comment]
Closed as part of https://github.com/alwindoss/morse/pull/18
